---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vclusters.openvc.dev
  resources:
  - vclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vclusters.openvc.dev
  resources:
  - vclusters/finalizers
  verbs:
  - update
- apiGroups:
  - vclusters.openvc.dev
  resources:
  - vclusters/status
  verbs:
  - get
  - patch
  - update
